# ~/.zshrc: zsh startup with oh-my-zsh, a function, and a secret.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git docker)
source $ZSH/oh-my-zsh.sh
export EDITOR=nvim
precmd() {
  print -Pn "\e]0;%n@%m: %~\a"
}
setopt HIST_IGNORE_DUPS
autoload -Uz compinit && compinit
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI_TESTCANARY2
