[package]
name = "configctl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "configctl: Linux-first environment manager (P1: read-only discovery)"

[dependencies]
configctl-core = { path = "../configctl-core" }
configctl-discovery = { path = "../configctl-discovery" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }
rpassword = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "configctl"
path = "src/main.rs"

[lib]
name = "configctl_cli"
path = "src/lib.rs"
